### ISSUE TITLE
Timeout issue

### ISSUE THREAD

**Issue by snowbordheathen** [taxjar/taxjar-java#13]
We've increased the timeout up to 5 minutes, but the server is still timing out after only 30 seconds.

11:47:13.768 [] [main] INFO   listOrders()
11:47:43.168 [] [main] INFO   failed: com.taxjar.exception.TaxjarException: Service Unavailable - Request Timed Out
        at com.taxjar.Taxjar.listOrders()

This happens almost 100% of the time on our linux production environment. Happens much less on our dev environments. Not really sure why that would be the case.

We've had to set the program to run hourly until it works each day. Which is obviously not optimal. Occasionally it takes over 24hrs to get a success. But it always takes at least 5-10 tries before the sever responds correctly.  Normally if we run it immediately after an error it works.

Thoughts?

**Comment by fastdivision** [comment]
@snowbordheathen Currently our API will return a timeout for this endpoint if the request takes longer than 30 seconds to complete. Are you filtering by a specific date range via `from_transaction_date` and `to_transaction_date`? How many orders do you generally get back? It may help to share this issue directly with our support team so we can review the API requests for your TaxJar account.
