### ISSUE TITLE
Transactions still bleeding from one merchant to another (multi-threaded issue)

### ISSUE THREAD

**Issue by perrytew** [taxjar/taxjar-java#18]
Hey.  This is a follow up to issue #14.

We just had two more transactions from one merchant go into another merchant's TaxJar account.

I've reviewed the code and found another area of concern. 
Within com.taxjar.TaxJar.java, the variable apiService is static.  That variable is configured via a retrofit object that uses client credentials. 

I've removed the static modifier for this variable and recompiled without issue.  If there's no compelling reason to have that variable static, would you please consider removing the static modifier to eliminate another source of cross threading contamination?

Regards,
Perry Tew

**Comment by ScottRudiger** [comment]
Thanks for reporting the issue @perrytew. We'll get a fix in shortly. 👍

**Comment by perrytew** [comment]
Thanks Scott!
