### ISSUE TITLE
Why do you use Float instead of BigDecimal

### ISSUE THREAD

**Issue by ucjonathan** [taxjar/taxjar-java#20]
Why use Float instead of BigDecimal in your Tax object?

**Comment by ScottRudiger** [comment]
@ucjonathan thanks for the question.

We use BigDecimal / arbitrary-precision decimal arithmetic internally for calculating sales tax.

> https://developers.taxjar.com/integrations/sales-tax-calculations/#section-amount
> You’ll notice our API documentation classifies amounts as long, referring to the long double data type from languages such as C. Behind the scenes we use BigDecimal when working with monetary values for highly accurate calculations.

However, we return back floats / decimals in the API response, typically around 2-5 decimal places. See attributes and examples [here](https://developers.taxjar.com/api/reference/#post-calculate-sales-tax-for-an-order).

**Comment by ucjonathan** [comment]
@ScottRudiger Would you consider changing it in the Java SDK to BigDecimal from Float to remove any possibility of precision issues arising?  The serialization frameworks certainly handle BigDecimal without any issues.

**Comment by ScottRudiger** [comment]
@ucjonathan Sorry for the delay; we discussed this internally and decided to keep it as float in the Java API client. We may consider changing it in the future, but for now I'll close this issue. Still, feel free to comment here again with any further considerations on this.
