### ISSUE TITLE
Tax Calculations API call return NullPointer Error during TaxJar API downtime

### ISSUE THREAD

**Issue by BasileKoko** [taxjar/taxjar-java#35]
On "2021-12-07T23:15:20.485Z" UTC, during [TaxJar outage](https://status.taxjar.com/uptime) due to AWS downtime, some our calls to Tax Calculations API return nullPointer error (see logs below). It appears that the TaxJarClient Java class [**TaxjarException**](https://github.com/taxjar/taxjar-java/blob/master/src/main/java/com/taxjar/exception/TaxjarException.java) does not handle properly `null errorMessage`.
We are using `taxjar-java:5.0.1`

We noticed that your [Exception tests](https://github.com/taxjar/taxjar-java/blob/master/src/test/java/com/taxjar/exception/ExceptionTest.java) covers `empty json` but it does not test for `null json`.
Could you please improve the class [**TaxjarException**](https://github.com/taxjar/taxjar-java/blob/master/src/main/java/com/taxjar/exception/TaxjarException.java) to handle null ErrorMessage? 

**testEmptyJson:**
`public void testEmptyJson() {
    String json = "{}";
    TaxjarException e = new TaxjarException(json);
    assertTrue(e instanceof TaxjarException);
    assertEquals(json, e.getMessage());
    assertEquals((Integer) 0, e.getStatusCode());
}`

**LOGS:**
`error.stack_trace: "java.lang.NullPointerException: null 	at com.taxjar.exception.TaxjarException.parseMessage(TaxjarException.java:29) 	at com.taxjar.exception.TaxjarException.<init>(TaxjarException.java:16) 	at com.taxjar.exception.TaxjarException.<init>(TaxjarException.java:12) 	at com.taxjar.net.ApiRequest.execute(ApiRequest.java:23) 	at com.taxjar.Taxjar.taxForOrder(Taxjar.java:170) 	at ***.**.**.***.api.tax.taxjar.TaxJarClient.calculateTax(TaxJarClient.java:49)`

**Comment by dallendalton** [comment]
This has been fixed with [5.0.3](https://github.com/taxjar/taxjar-java/releases/tag/v5.0.3) release.
