### ISSUE TITLE
JsonSyntaxException

### ISSUE THREAD

**Issue by themetaschemer** [taxjar/taxjar-java#5]
Hi,

I get the following exception after I have submitted about 100 or so transactions taxjar transactions (I submit them in bulk, one day at a time). Once the error starts most of the subsequent get the same error. When I resubmit the missed transactions after a minute or so, they all go through. Any help will be appreciated. 

Thanks.

 com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive
         at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:913)
         at com.google.gson.Gson.fromJson(Gson.java:887)
         at com.google.gson.Gson.fromJson(Gson.java:852)
         at com.google.gson.Gson.fromJson(Gson.java:801)
         at com.google.gson.Gson.fromJson(Gson.java:773)
         at com.taxjar.exception.TaxjarException.<init>(TaxjarException.java:12)
         at com.taxjar.Taxjar.createOrder(Taxjar.java:410)

**Comment by fastdivision** [comment]
@themetaschemer This might be happening because our API isn't returning a valid JSON response for `429 Too Many Requests (Rate Limit Exceeded)` errors. We're seeing a similar issue in our [Python API client](https://github.com/taxjar/taxjar-python/issues/9). We've prioritized the issue and we're hoping to fix it soon. Thanks for your patience!

**Comment by fastdivision** [comment]
Our API should now return a valid JSON error response for 429 errors with `error` and `detail` attributes included. Thank you!

**Comment by themetaschemer** [comment]
Awesome. Thanks for letting me know!
Best,
Anurag. 
    On Thursday, February 21, 2019, 12:09:43 PM PST, Jake Johnson <notifications@github.com> wrote:  
 
 
Our API should now return a valid JSON error response for 429 errors with error and detail attributes included. Thank you!
