### ISSUE TITLE
SerializedName issue in Breakdown class

### ISSUE THREAD

**Issue by SteveAtReactorOne** [taxjar/taxjar-java#8]
There is a mismatch between the JSON response to a "Tax for Order" request and the corresponding java classes in the 1.3.0 release of the client. 

 From Breakdown.java:
```
    @SerializedName("special_district_tax_rate")
    Float specialDistrictTaxRate;
```

The JSON response contains:
`            "special_tax_rate": 0,
`

From BreakdownLineItem,
```
    @SerializedName("state_tax_rate")
    Float stateTaxRate;
```

And the corresponding field in the JSON response:
`
                    "state_sales_tax_rate": 0.06,
`

**Comment by fastdivision** [comment]
Thanks for reporting these issues, @SteveAtReactorOne. I'll get this fixed shortly and update the specs to check for these attributes.
